spring.application.name=betapi
server.port=8080

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200,http://localhost:4201

# Google Sheets Configuration
google.spreadsheet.id=1UmG_jaQg3Eb3clMDcNYnTcZmFvCMBAR8rWoc0KTcc-4
google.spreadsheet.fifa2026.id=1bwOfsEm7Om9HulZt0YbJkjUrTsMGZ6MwDcc1UnE9yfo
google.spreadsheet.user.config.id=1nBAJHR5U8foG2ncSG1287J5N_88VjqvEz7OBiCzf5iA
google.spreadsheet.range=Sheet1!A1:H105
google.credentials.file.path=src/main/resources/credentials.json

# OAuth2 Resource Server Configuration (Google)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

# Logging
logging.level.com.example.betapi=INFO
logging.level.org.springframework.security=DEBUG
