spring.application.name=betapi
server.port=8080

# Google Sheets Configuration
google.spreadsheet.id=1UmG_jaQg3Eb3clMDcNYnTcZmFvCMBAR8rWoc0KTcc-4
google.spreadsheet.range=Sheet1!A1:G100
google.credentials.file.path=src/main/resources/credentials.json

# OAuth2 Resource Server Configuration (Google)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

# Logging
logging.level.com.example.betapi=INFO
logging.level.org.springframework.security=DEBUG
